[package]
name = "configable"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
name = "configable"

[dependencies]
config_derive = { path = "./config_derive" }
tikv_util = { path = "../tikv_util" }
